# Going Digital

> Digital archaeology should exist to assist us in the performance of archaeology as a whole. It should not be a secret knowledge, nor a distinct school of thought, but rather simply seen as archaeology done well, using all of the tools available to and in better recovering, understanding and presenting the past. In the end, there is no such thing as digital archaeology. What exists, or at least what should exist, are intelligent and practical ways of applying the use of computers to archaeology that better enable us to pursue both our theoretical questions and our methodological applications. [@evans2006digital]

While we agree with the first part of the sentiment, the second part is rather up for debate. Digital tools exist in a meshwork of legal and cultural obligations, and moreso than any other tool humans have yet come up with, have the capability to exert their own agency upon the user. Digital tools and their use are not theory-free or without theoretical implications. There is no such thing as neutral, when digital tools are employed.

In this section, we suggest that digital archaeology is akin to work at the intersection of art and public archaeology and digital humanities. We then provide you the necessary basics for setting up your own digital archaeological practice.

## So what is Digital Archaeology?

If you are holding this book in your hands, via a device or on paper, or looking at it on your desktop, you might wonder why we feel it necessary to even ask the question. It is important at the outset to make the argument that digital archaeology is not about 'mere' tool use. Andrew Goldstone in _Debates in the Digital Humanities_ discusses this tension. He has found (and Lincoln Mullen concurs with regard to his own teaching) that our current optimism about teaching technical facility is misplaced. Tools first, context second doesn't work. Alternatively, theory first doesn't seem to work either. And finally, for anything to work at all, datasets have to be curated and carefully pruned for their pedagogical value. We can't simply turn students loose on a dataset (or worse, ask them to build their own) and expect 'learning' to happen. INSERT GOLDSTONE and MULLEN REFERENCES

Our approach in this volume is to resolve that seeming paradox by providing not just the tools, and not just the data, but also the computer itself. Archaeologically, this puts our volume in dialog with the work of scholars such as Ben Marwick, who makes available with his research the code, the dependencies, and sometimes, an entire virtual machine, to enable other scholars to replicate, reuse, or dispute his conclusions. We want you to reuse our code, to study it, and to improve upon it. We want you to annotate our pages, and point out our errors. For us, digital archaeology is not the mere use of computational tools to answer archaeological questions. Rather, it is to enable the audience for archaeological thinking to enter into conversation with us, and to *do* archaeology for themselves.

Digital archaeology is necessarily a public archaeology. This is its principal difference with what has come before, for never forget, there has been at least a half-century of innovative use of computational power for archaeological knowledge building.

### Is digital archaeology part of the digital humanities?

The Computer Applications in Archaeology Conference has been publishing its proceedings since 1973. Archaeologists have been running simulations, doing spatial analysis, clustering, imaging, geophysicing, 3d modeling, neutron activation analyzing, x-tent modeling , etc, for what seems like ages.

Surely, then, digital archaeologists are digital humanists too? Trevor Owens, a digital archivist, draws attention to the purpose behind one's use of computational power – generative discovery versus justification of an hypothesis. Discovery marks out the digital humanist whilst justification signals the humanist who uses computers. Discovery and justification are critically different concepts. For Owens, if we are using computational power to deform our texts, then we are trying to see things in a new light, to create new juxtapositions, to spark new insight. Stephen Ramsay talks about this too in Reading Machines (2011: 33), discussing the work of Jerome McGann and Lisa Samuels: "Reading a poem backward is like viewing the face of a watch sideways – a way of unleashing the potentialities that altered perspectives may reveal". This kind of reading of data (especially, but not necessarily, through digital manipulation), does not happen very much at all in archaeology. If 'deformance' is a key sign of the digital humanities, then digital archaeologists are not digital humanists. Owen's point isn't to signal who's in or who's out, but rather to draw attention to the fact that:

> When we separate out the the context of discovery and exploration from the context of justification we end up clarifying the terms of our conversation. There is a huge difference between "here is an interesting way of thinking about this" and "This evidence supports this claim."

This is important in the wider conversation concerning how we evaluate digital scholarship. We've used computers in archaeology for decades to try to justify or otherwise connect our leaps of logic and faith, spanning the gap between our data and the stories we'd like to tell. A digital archaeology that sat within the digital humanities would worry less about hypothesis testing, and concentrate more on discovery and generation, of 'interesting way[s] of thinking about this'.

### Archaeological Glitch Art

Bill Caraher is a leading thinker on the implications and practice of digital archaeology. In a post on archaeological glitch art Caraher changed file extensions to fiddle about in the insides of images of archaeological maps. He then looked at them again as images:

> The idea ... is to combine computer code and human codes to transform our computer mediated image of archaeological reality in unpredictable ways. The process is remarkably similar to analyzing the site via the GIS where we take the "natural" landscape and transform it into a series of symbols, lines, and text. By manipulating the code that produces these images in both random and patterned ways, we manipulate the meaning of the image and the way in which these images communicate information to the viewer. We problematize the process and manifestation of mediating between the experienced landscape and its representation as archaeological data.

Similarly, Graham's work in representing archaeological data in sound (a literal auditory metaphor) translates movement over space (or through time) into a soundscape of tones, freeing us from the tyranny of the screen and visual modes of knowing that often occlude more than they reveal (for instance, our Western-framed understanding of the top of the page or screen as 'north' means we privilege visual patterns in the vertical dimension over the horizontal REF).

### The 'cool' factor
Alan Liu, in 2004, wondered what the role of the arts and humanities was in an age of knowledge work, of deliverables, of an historical event horizon that only goes back the last financial quarter.  He examined the idea of 'knowledge work' and teased out how much of the driving force behind it is in pursuit of the 'cool'. Through a deft plumbing of the history of the early internet (and in particular, riffing on Netscape's 'what's cool?' page from 1996 and their inability to define it except to say that they'd know it when they saw it ), Liu argues that cool is 'the aporia of information… cool is information designed to resist information [emphasis original]… information fed back into its own signal to create a standing interference pattern, a paradox pattern' (Liu, 2004: 179).  The latest web design, the latest app, the latest R package for statistics, the latest acronym on Twitter where all the digital humanists play: cool, and dividing the world.

That is, Liu argued that 'cool' was amongst other things a politics of knowledge work, a practice and ethos. He wondered how we might 'challenge knowledge work to open a space, as yet culturally sterile (coopted, jejune, anarchistic, terroristic), for a more humane hack of contemporary knowledge?' (Liu 2004: 9). Liu goes on to discuss how the tensions of 'cool' in knowledge work (for us, read: digital archaeology) also intersects with an ethos of the unknown, that is, of knowledge workers who work nowhere else somehow manage to stand outside that system of knowledge production. (Is alt-ac 'alt' partially because it is the cool work?). This matters for us as archaeologists. There are many 'cool' things happening in digital archaeology that somehow do not penetrate into the mainstream (such as it is). The utilitarian dots-on-a-map were once cool, but are now pedestrian. The 'cool' things that could be, linger on the fringes. If they did not, they wouldn't be cool, one supposes. They resist.

To get that more humane hack that Liu seeks, Liu suggests that the historical depth that the humanities provides counters the shallowness of cool:

> The humanities thus have an explanation for the new arts of the information age, whose inheritance of a frantic sequence of artistic modernisms, postmodernisms, and post-postmodernists is otherwise only a displaced encounter with the raw process of historicity. Inversely, the arts offer the humanities serious ways of engaging – both practically and theoretically- with "cool". Together, the humanities and arts might be able to offer a persuasive argument for the humane arts in the age of knowledge work. 2004:381.

In which case, the emergence of digital archaeologists and historians in the last decade might be the loci of the humane hacks – if we move into that space where we engage the arts. Indeed, the seminal anthropologist Tim Ingold makes this very argument with reference to his own arc as a scholar, 'From Science to Art and Back Again':

>  Revisiting science and art: which is more ecological now? Why is art leading the way in promoting radical ecological awareness? The goals of today's science are modelling, prediction and control. Is that why we turn to art to rediscover the humility that science has lost? 

We need to be making art. Digital archaeology naturally pushes in that direction.

### Takeaways

+ Digital archaeology is a public archaeology
+ Digital archaeology is more often about deformance rather than justification
+ In that deformative practice, it is in some ways extremely aligned with artistic ways of knowing
+ Digital archaeology is part of the digital humanities, and in many ways, presaged current debates and trends in that field.

All of these aspects of digital archaeology exist along a continuum. In the remainder of this chapter, we discuss the necessary skills to get you to the point where you can begin to wonder about deformation and the public entanglement with your work.

##  Project management basics 

blah

## Github & Version control

blah 

### discussion

### exercises


## Failing Productively

blah

### discussion

### exercises


## Open Notebook Research & Scholarly Communication

blah

### discussion

### exercises

## Introduction to Digital Libraries, Archives & Repositories

yadda

## Command Line Methods for Working with APIs

yadda

### Working with Open Context

yadda

### Working with Omeka

yadda

### Working with tDAR

yadda

### Working with ADS 

### Exercises

yadda

## The Ethics of Big Data in Archaeology 

Ethics! Lots of Ethics!

### discussion

### exercises
