## The Human Problem

<div class = rmdcaution> _This section is under development_. </div>

A key to success in using, remixing, and sharing data openly is communicating effectively with colleagues and other stakeholders. Although rigorous research will take you part of the way in developing work that is well-regarded by other scholars, it will not happen in a vacuum. You must be the best advocate for your own work, and for digital archaeology as a methodology.

Whether you are utilizing data that already existed or creating a totally new dataset, your work impacts colleagues, and it is important to build not only a technical framework but social supports for your work. Another way of understanding this is that you are responsible for ensuring you actually reach the audience you identified while following Appleford and Giuliano's project design principles (described in chapter 01.2). A successful digital archaeology project is one which is well-understood and well-regarded by colleagues. In the following section I will describe how to frame digital archaeology work for colleagues and others who may be interested or impacted by it, and share three key tools for establishing boundaries and expectations for your project.

### The Two-Sentence Pitch

Whether you are building a large, multi-faceted, multi-scholar project or experimenting on your own, you need to be ready to explain your work's value. By the time you talk to a colleague about it, you should have a two sentence pitch. Being prepared to explain why your digital archaeology project is valuable is not only important for you to maintain the resources to continue your work, but helps build support for digital archaeology scholarship in the community. If there is one planning task you do, do this.

> Example project: [Graham and Ellenberger's 2017 Heritage Jam Entry](http://www.heritagejam.org/new-blog/2017/10/25/old-bones-daily-shawn-graham-and-kate-ellenberger)
> Two-Sentence Pitch: This is the first part of our research on how 19th century newspapers in Western Quebec and northern New York State depicted human remains and archaeology. We used language we found in the newspaper text to generate a realistic-looking fictional newspaper that is different every time you load it. 

> Example project: [Ellenberger's Museum Tablet Tour](http://kateellenberger.com/digital-archaeology/museum-tablet-tour-2014/)
> Two-Sentence Pitch: I made an accessible digital tour for the visible storage display at the University Art Museum so that visitors could learn more about the objects, and read interpretations written by students and faculty. It was rewarding to build the first digital database the museum has used and be able to infuse some of my anthropological values into its design.

<!-- What's below is a messy outline and not reflective of the structure I'm going to write -->

### Consulting Colleagues and Stakeholders

<!-- Matching format to scholarly audience -->
For many of us, the main audience of our research is our colleagues. But colleagues is about as vague and useless a term as "the public" and so when you develop a new project you should pin down (for yourself) the scholarly topics that your work will contribute to, and some examples of individuals who do related work. This will not only help you strategize who to seek out when presenting or publishing your work, but will give you an opportunity to examine what sorts of work are valued in those communities. For example, public archaeologists often present their work at scholarly conferences but may never publish them in peer-reviewed journals, and in digital archaeology the norm is to share data and documentation online. Be ready to either make a contribution in the form your colleagues will recognize as valuable or explain why you chose something different. Furthermore, don't forget that most colleagues will not have the technical skills you develop during your digital archaeology project so prepare to explain yourself 

<!-- Maintaining collegiality with the data originator and related parties -->
If you are using legacy data, such as excavation data someone else created, do not assume that just because you can access it that you can do with it whatever you want without consequence. Data sharing norms are not consistent in international archaeology. Do not assume you are going to get anyone's blessing, particularly if your work might be interpreted as a critique of the originator of the data, or other scholars whose work is in the same scholarly area. If it is possible to contact the originator of the data and give them a two-sentence pitch about your intended work, do it, and do it early. (If you are a non-traditional or early career researcher, you should be especially attentive to this.) When you contact them explain yourself without assuming they are interested in the technical aspects unless they ask. The sheer volume of data produced by archaeologists and the time it takes to code and manage that data leads us to be slow to adopt new technologies, even if we are on board with them. It is easy to think of all colleagues as having the same competencies, and forget how alienating jargon can be, even to fellow professionals. If your plans change radically or if your derivative works will be shared in a way you have not discussed with them, follow up briefly. This is both professional courtesy and ethical practice. 

<!-- Non-colleague stakeholders -->
Even highly technical or abstract work can impact people beyond the scholarly realm (see chapter 01.8 for further discussion of ethics). Two common examples of external stakeholders are descendant communities, whose ancestors we characterize, and local communities, whose property values and sense of heritage we may affect. You are the expert in your own project's modern context and significance, so think carefully about what your work will mean for people whose interest is not solely in the academic rigor of your scholarship.

<!-- COMMENT OUT UNUSED NOTES FOR NOW
  + Address the importance of this planning for early career and contingent researchers and students in particular
2. Stakeholders Beyond Archaeology
  + Example: Cemetery project
  + Sometimes stakeholders are individuals, sometimes they are institutions or vague groups/entities; address who to choose and the stakes of deciding this
  + The power of informal working groups for getting feedback and direction
  + Managing expectations
  + Sharing outputs and picking appropriate formats 
-->

### Making a Plan

In this section I will give you three more tools for planning and managing the human aspect of a project. None of these need to be exhaustive or perfect, and preparing on a basic level for how you will go about managing the project will save you time and effort in the long run. I have organized these tools from informal to formal.

#### Consultation

<!-- I need to make everything after this comment less trite and focus on giving a template for people to apply -->

Consultation is one of the most important things you can do to make your project successful. Discuss your idea with trusted colleagues first, and if applicable, with stakeholders outside the field, before you begin manipulating data. Absolutely do not publicly share results of a project before speaking to a single colleague or stakeholder about it. Informal working groups of colleagues are invaluable and you should use them.

#### Strategy Document


#### Policy Document



### Persisting and Adapting your Plan

If you do most of your research on your own or improvise often, you may not be used to following a plan. Even if your plan is loose and flexible, I strongly urge you to follow one. It can be three sentences long, but those are three sentences worth having when you get stuck. The biggest difficulties people have in continuing their digital archaeology projects are with people, not technology, so this aspect of project planning deserves attention. Everyone has heard of a colleague who believes someone else's work is infringing on their intellectual property in some way, or colleagues not believing certain projects have intellectual value, or someone who used data in a way that upset the colleagues or interlocutors they got it from. Try to avoid that. Most of the time you can.

<!-- I need to make this less trite -->

When you reach a roadblock that needs to be solved by communicating with other scholars or stakeholders, troubleshoot it using the logic and dedication you would in solving a technical issue.

Exercises

1. Write a two-sentence pitch for your most recent, already-completed project. Save that text in a file with your project data or technical plan.
2. Write a two-sentence pitch for your dream project. Convince yourself in two sentences of why it is worthwhile to pursue.
3. Identify a person who is more senior than you who might be interested in your dream project. What could you learn from them about the technical skills, data, or audience of your project? Revise your two-sentence pitch as if you were speaking to them specifically. 