## Designing Data Collection and Curation

<div class = rmdcaution> _This section is under development_. </div>

In teaching, there is a concept called 'backwards design', where you design your lesson from the end point you wish your students to achieve. The same is true of data. Knowing that archaeology is destructive, and that the processes of archaeology _creates_ new kinds of artefacts (drawings, photos, record sheets, labels, and so on), we need to start at the end. Ideally, it is an end point that will allow someone else to reconsider the archaeological record that you have created. As Gavin Lucas @lucas2012understand writes, the idea of an 'archaeological record' is a three-fold, trinity-like concept-

- the material culture broadly understood
- the 'formation theory' of how that material culture came to be
- and the materialization of the construction of that material culture in the present: our archive

And so, we will begin this section on data collection by thinking through where the _things_ are going to go.

<!-- need a graphic here? circular relationship of destination database structure and collection structure. Also, maybe rework that first paragraph to make it make sense in circular fashion.-->

**Modes of collection**

While this is, after all, the *Open* ***Digital*** *Archaeology Textbook Environment*, don't discount the option of analog data collection. Like so many other choices you'll make when setting up a digital archaeology project, there's no correct default here; it's dependent on your particular needs and constraints.

*Paper to digital*
Sometimes the most straightforward way to collect data in the field is to write it on paper. Paper forms can't run out of batteries. Data loss and integrity issues are still real, but massive data loss may be less of a threat when working with paper, depending on backup mechanisms.

It's usually a good choice to mirror the format of the destination database on the input form.

*Born digital*
Collecting your data digitally holds significant advantages. If you've settled on the structure of your destination database, digital data collection can seamlessly integrate information, eliminating extra steps and reducing opportunities for transcription errors.

The landscape for mobile data collection in archaeology has flourished in recent years. Archaeologists now have access to a broad spectrum of data collection options, from off-the-shelf mobile data collection applications custom designed to meet to meet the needs of specific projects and organizations to assembling a suite of free, open source tools as needed.

The trick in designing digital data collection is to set limits without over-constraining. Typing data into fields in an Excel spreadsheet is digital data collection, sure, but setting up controls to standardize data entry is complicated and fragile.<sup>[1](#myfootnote1)</sup>


Whether you're designing data collection on paper or on a device, give yourself time to test it out. A dry run with real (or close to real) data can illuminate pain points for data collection now and analysis later.

Importance of training

**Creating structure**

**Where to put your data**

Earlier in this section we discussed digital preservation. <!-- link back to part 2 intro.  --> We covered the basics of what it takes for stable, reusable data, but where will it live? Let's talk about *repositories.* A digital repository can be short-term or long-term.

Questions to consider:
- If you're planning to curate your own digital materials and hope to keep them safe for a long time, are you prepared to do regular checks and maintenance?
- What do you want to save? It might not be *everything*.

If you're looking toward an outside repository:
- Does it have room for your data? Is your research or data within the scope of mission for that repository?
- Does the repository have special requirements for format or preparation?
- Does the repository charge a fee to deposit material? Have you built it into your budget?
- Does the repository itself have a plan for long-term sustainability? What happens to the data if its host organization is dissolved?
- Does the repository have plans for migrating and maintaining your files?


**Some Existing Repositories for Archaeological Data and/or Digital Projects**  
Each option below meets differing needs.  

<!-- These need descriptions -->
[Zenodo](https://zenodo.org/)  
[tDAR](https://www.tdar.org/)  
[ADS](http://www.archaeologydataservice.ac.uk/)  
Publishing through [Open Context](https://opencontext.org/) at the California Digital Library  
[Internet Archive](https://archive.org/)
University libraries  
State or local government archives and libraries  
<!-- Somewhere in this section it would be good to differentiate kinds of projects and data. Field data vs. interpretive web projects etc. This is probably getting muddled right now.  -->



<a name="myfootnote1">1</a>: If you find yourself engineering a complicated spreadsheet with dependent picklists and formulas for relationships, this may be a sign that you're using the wrong tool.
### discussion

### exercises
