## Arranging and Storing Data for the Long Haul (Databases!)


Once you’ve collected data according to your plan and structure, you’ll need a way to connect it all together in a way that allows you and other researchers to use it, hopefully for some time to come.

So what *is* a database and which one should you use?

Choosing a format:
A lot of people have a lot of opinions on good database platforms, horrible ones, and everything in between. But there is no universally right answer and a lot depends on technical resources and level of experience. That is to say, in many cases, a relational database is the strongest option, but handling information well in spreadsheets may met your needs and the needs of other researchers if implemented well. Our organizations may dictate software platforms we're permitted to use, and often that's Microsoft Access or Excel.



### discussion

### exercises

Data Organization in Spreadsheets for Social Scientists

http://www.datacarpentry.org/spreadsheets-socialsci/

SQL for Social Science Data
http://www.datacarpentry.org/sql-socialsci/
