## What is Web Mapping?
A Web map is a geographic visualization that is supported by computational infrastructures. This form of mapping is fundamentally *powered* by the Web [Axismap, 2018](http://www.axismaps.com/guide/web/what-is-a-web-map/). It should come as no surprise that ubiquity of Web maps correlates with development of Web 2.0, a marked transformation in the way that that we interact with the Internet [Cristina Aced, 2013](https://www.researchgate.net/publication/266672416_Web_20_the_origin_of_the_word_that_has_changed_the_way_we_understand_public_relations).

As [Darcy DiNucci](http://darcyd.com/fragmented_future.pdf) remarked in 1999, content loading into a browser as 'static screenfuls is only an embryo of the Web to come'. Web 2.0, thus is characterized by 'interactivity', 'two-way communication' often through devices that are 'Internet-connected' and a greater awareness amongst developers of 'user experience' and 'interface'. Whereas the first iteration of the Web required advanced training to create a website, Web 2.0, as is often claimed, requires little or no expert knowledge to make a Web-ready 'thing' such as a website, a blog, or a Wiki. This is the context in which Web mapping, that is the Web-based visualization of geographic information became popularized.

One can argue that Web maps narrow the distance between professional map makers and non-specialist makers; yet some scholars have expressed concerns on the quality of geographic data that are now frequently and widely shared on the Web [ref-name](ref). Collaborative online platforms such as OpenStreetMap, for example, have drawn attention to the social dimension of knowledge making; how accurate is information that a lay-person or particular interest community has uploaded? Can we make real-world decisions based on those data? [D Bégin, R Devillers, S Roche, 2013](https://www.int-arch-photogramm-remote-sens-spatial-inf-sci.net/XL-2-W1/149/2013/isprsarchives-XL-2-W1-149-2013.pdf) suggest that volunteered geographic information reflects 'contributors’ motivation and individual preferences in selecting mapped features and delineating mapped areas', a situation that can enable scholars in examining and assessing the quality of those data.

For archaeologists, Web maps and publishing geographic information present challenges and opportunities. Archaeologists are aware that the data they collect through field studies often contain sensitive location information. They often express concern that publishing location information on sites of archaeological and historical interest can facilitate, if not result in, the destruction of those sites through looting. Looting and illegal trafficking of archaeological artefacts and human bones is an issue observed in many places [ref-name](ref)

Recent developments in geovisual analytics that leverage the spatial dimension in data suggest that scholars can work with, and meaningfully analyze these data even where they contain sensitive location information [Andrienko et al 2007](ref). This situation opens enormous opportunities for archaeologists to develop tools that are appropriate for the publication of archaeological data. In the next section, we build upon the ethos of 'openness' and present an overview of map services, followed by a guide to making an interactive Web map with the Leaflet library. For an example of a Leaflet Web map, check out [Open Context](www.opencontext.org).

### Overview of Map Services
Tiled map service and [Web Map Service](http://www.opengeospatial.org/standards/wms) are two forms of Web-based mapping. A WMS is an interface that enables us (the clients) to request specific maps i.e. visual representations of geographic information from a geospatial database. The WMS server is called via a Universal Resource Link (URL) through an Internet-enabled desktop GIS. A request typically consists of the geographic layer (e.g. theme) and geographic area of interest. The response to a request results in *geo-registered map images* that are displayed and queried within a browser. Because the map is dynamically drawn upon request, and because the server typically uses the most current information from several layers in the geospatial database, WMS maps tend to load slowly. [Toporama] (http://wms.ess-ws.nrcan.gc.ca/wms/toporama_en) is an example of a WMS server for Canadian topographic themes. [add image for WMS architecture?]

Tile map services such as [TillMill Project](http://tilemill-project.github.io/tilemill/docs/crashcourse/introduction/), [OpenStreetMap](https://www.openstreetmap.org/), [CartoDB](www.carto.com), and [Stamen](http://maps.stamen.com) all use a rasterized image that is divided into 256 x 256 adjacent pixel images or 'tiles'. Once generated, the set of tiles are stored on disk and thus they can be distributed rapidly to large numbers of simultaneous requests. Tiled maps shift attention to map aesthetics and smooth map navigation, trading in functionality such as layer order, map scale and projection. [Alex Urquhart](http://alexurquhart.github.io/free-tiles/) maintains a list of free tile services. [add image for tiles?]

### Making a Web map with Leaflet
[Leaflet](http://leafletjs.com/) is a JavaScipt library developed by [Vladimir Agafonkin](https://vimeo.com/106112939) for use with tiled maps. Launched in 2008, Leaflet has become widely used in tile Web mapping because it is easy to customize and develop interactivity with map elements, and because of its speed and simplicity when compared to a dynamically drawn WMS map.

To make your own interactive Web map with Leaflet, you need the following:

1) geocoded data saved as csv
2) GitHub account
3) tile map service

### exercises
