## Virtual Archaeology

<div class = rmdcaution> _This section is under development_. </div>

In the 1980’s during the hype of futuristic movies like Tron (the original - date), War Games (date) and Lawnmower Man (date) in which virtual reality played a key role in transporting characters and audiences into an all immersive virtual space, the notion of Virtual Archaeology was born, or more specifically, coined. Virtual Archaeology saw its beginnings in what is now Computational Archaeology, or basically, the use of computer science in archaeology. As it is today, and very much represented within this textbook, computer archaeology is divided into two distinct fields; a) the use of mathematical data to analyze and predict archaeological information and b) the visualization of that data into 2D, 3D and 3D printed (re)visualizations, which are representational of the known and constructed knowledge archaeologists create when we analyzing the context, landscape and time stratification of an archaeological site. When archaeologist Paul Reilly coined the term in 1987, before the widespread introduction of personal computers, his intent was to bring to light that visualizing archaeological data beyond just graphs and charts, helped to enhance and communicate the narratives buried within the archaeological sites we excavate and the knowledge we were constructing through the analysis of those limited data sets. The key however to Reilly’s notion was that the raw, scientific, archaeological data, however scarce, still needed to be the starting point of the virtual representation.

In this chapter, we will explore the theory and method of virtual archaeology and how it relates to the broader notion of Digital Archaeology.

### Basic principles

Archaeological narratives, the stories we create in order to explain the material culture we find within archaeological sites, must begin with data, no matter how small, that we derive from the archaeological landscape.

To explain our hypothesis and to give credence to our virtual (re)imagination of the archaeological material, whether it is an object, landscape or built environment, we must and can use a combination of theories and methods to support our virtualization of the archaeological past.

Virtual archaeology is just not the seen. It is felt, smelt, heard, it has texture and weight, it has a narrative. It can be accessible and restrictive depending on the wishes of the descendent caretakers or the needs of the greater public. Virtual archaeology is not virtual reality but a means in which to experience the archaeological past phenomenologically.

### Main Challenge

Throughout this volume on archaeology, the authors and the examples presented, have laid out what Digital Archaeology is. The acquisition of data from the archaeological landscape, the visualization of that data through the technology and techniques best suited for the type of data being captured and communicated, as well as the means in which Digital Archaeology is partially or fully integrated within a broader more digitally dependent archaeological process.

Virtual archaeology relies more heavily on the construction of new knowledge through the making of 2D images, 3D models or 3D printed objects. What does that mean? As archaeologists, we interpret the archaeological material that reveals itself. We draw from past knowledge and experience; what we have learned in school, on other archaeological excavations, what others have said on the subject before us, but more importantly what the object, landscape or built environment says to us personally. 

Say more…

### The Archaeological Narrative

What is the “archaeological unknown”? When an archaeological artifact, landscape or built structured is (re)discovered, its context is partially or fully missing. Archaeologists have to then develop a “best guess” theory of the meaning, motivation and context of the archaeological material based on experience, known knowledge and creative interpretation. In many ways it is detective work, sousing out who might have made the artifact, landscape or structure, why or what was the motivation and how did it come to rest in within a particular spot. Archaeologists usually use theories, developed by themselves or borrowed from other archaeologists to explain the who, what, why and how. As digital archaeology is in many ways about the interpretation of data points, there is always a scientific, quantifiable flavour to the interpretations or data generated through digital means. We as archaeologist, then source our toolkit of skills, knowledge and experience to paint an interpretation, visual, phenomenological or written, of the artifact and the data potentially associated with the object, landscape or structure.

In 1993, archaeologist Janet Spector wrote a highly influential paper entitled, “What this awl means: Feminist archaeology at a Wahpeton Dakota village”. Instead of methodically describing an artifact scientifically, a tradition in archaeology to give weight and authority to what the archaeologist is about to interpret, Spector chose to create a narrative, a living history if you like, of the artifact that was excavated (side box with a note to read the Spector article). The artifact, an awl, is used to make clothing and Spector narrated a story that brought the artifact and the person who many have used it, to life, virtually, in the readers mind. This fictional interpretation however was based on the cumulative scientific, anthropological and archaeological knowledge Spector sourced in order to (re)visualize one potential lifeway of this artifact. It was remarkable because Spector made this archaeological find accessible to a larger audience by creating a narrative which captured the essence of the artifact. Essentially, Spector has given us the permission to creatively interpret the archaeologically unknown, while still being grounded in traditional archaeological theory.
The thread throughout anthropologist Tim Ingold’s 2011 book, “Being Alive: Essays on Movement, Knowledge and Description” is that objects have their own narratives. That the world (the environment, plants, animals, humans…) come into contact with objects, add to the objects narrative and as time passes, those narratives are recorded physically upon the object but the meaning, the context, is lost. Additionally, Like the awl, artifacts were once raw material. That material, may it be wood, stone or the landscape, all have previous stories, like you do, that make up the object’s existence. When we work these raw materials to fashion a new object, like a pot, a spear point or a piece of art, the raw materials have their own way of imposing their narratives into the new object being created. Like a knot in a piece of wood, it forces the carpenter to change direction and accommodate or build upon the materials previous narrative (side box with a note to read the Ingold chapter on sawing a piece of wood). It is these course-corrections, or as Ingold describes them, wayfaring points, that helps us understand what the artifact may be, and mean within the context in which it was excavated.

A wayfaring point is really just a decision-making moment. An artifact is made, used and then discarded but in-between those key points in its lifeway, there are other smaller wayfaring stops which build upon the artifact, landscape or structures where the context or intent has been lost. Ingold also provides a way for us, as archaeologists, to make new meaning from the archaeologically unknown, as we (re)imagine artifacts, landscapes and ancient peoples within 2D, 3D or 3D printed form. The construction of unknown knowledge, or the creation of plausible narratives for those unknown wayfaring moments, helps to interpret the archaeological material. In many ways, we “make” new meaning when we create new narratives to fill in the gaps.

Take for instance, an Iroquoian Longhouse (side image of an excavated Iroquoian longhouse and a reconstructed one). Unlike the stone remnants of the great castles of Europe, or the Pyramids of Egypt, there are no lasting remains of longhouse structures other than the post-hole circles that represent where the wooden superstructure once stood but has now rotted into dirt. Nothing of these structures survive above the soil line, so in order to (re)visualize these grand structures archaeologists have to work closely with the current decedents to interpret the oral stories and histories of longhouses and how they were built as well as source whatever historical images or written accounts the first European voyagers made of their encounters with the Iroquoian populations. One might even look towards experimental archaeology (side box with a note on experimental archaeology) to understand what types of wood and bark would be used when (re)visualizing all the bits and pieces that haven’t survived in the archaeological record. 

As we are constructing in 2D or 3D, through a written or spoken narrative, we are reimagining based on the information available, what an artifact, landscape or structure would have looked like. We are “making” new knowledge, testing existing theories and creating an alternative narrative.

### Theoretical Pragmatism

Archaeology is a theory laden subject. There is no getting around it. Although archaeology is highly tactile, physical and applied, as archaeologists, we must harken back to established theories, notions and concepts to speak authoritatively in our interpretations.

The concept of Virtual Archaeology is almost 30 years old, yet it still suffers from a lack of theoretical grounding. Paul Reilly freely admits that coining the term “virtual archaeology” in the 1980’s has been problematic, especially now in the present, when virtual reality has come to represent in entertainment as well as science, a very real means of immersing oneself into an alternative, almost hyper-real world. Jeremy Huggett suggests it is because we “fetishize the technology” (2004), placing more emphasis on what the technology does instead of critically evaluating what information it provides. Further, in a generation that now consumes and produces information easily, alternative visions and voices, both critically sound and not, compete with an archaeologist driven narrative, thus consumers have become producers.

Well established archaeological theories support parts of the virtual archaeological method and practice, but there isn’t one theoretical approach we can wrap around virtual archaeology to ground it to the current concept of archaeological science, of which most of digital archaeology is born. There is however a “theoretical pragmatism”, derived from a humanistic and philosophical approach to understanding the archaeological landscape, that provides a freedom to pick and choose elements and parts of various archaeological theories to support a virtual archaeological interpretation.

Called “archaeological cabling”, Alyson Wylie, an archaeologist who has specialized in the philosophical notions in archaeology, provides a theoretical pragmatism that easily lends itself to the theory and practice of virtual archaeology. Quite simply, a rope, has many strands and when they are twined together, it makes for a stronger combined element. Virtual archaeology in many ways is a combination of multiple theories which helps to solidify 

### Phenomenology and Virtual Archaeology

blah
blah

### Lasting Considerations

blah
blah

### Creative Disruption in Archaeology

### Exercises

blah

## Archaeogaming

“Archaeogaming” is the study of archaeology both in and of games, largely focused on digital games (arcade cabinets, computer games, console games, etc.) but also including analog games (tabletop, pen-and-paper, cards, dice, etc.). Two major branches comprise archaeogaming: 1) representations of archaeology and archaeologists in games, and 2) treating games as archaeology themselves. 

### Archaeological Reception

Archaeologists and archaeological settings lend themselves easily to game design. Archaeologists have reasons to travel to exotic places, to go on adventures, to look for artifacts, and to engage with indigenous cultures. Game developers appropriate archaeological tropes for adventure storytelling, encouraging looting and commerce in artifacts. It is rare to find a game that accurately represents archaeologists and archaeology, and players must ask themselves how what is represented on-screen reflects modern interpretations of the field and its practitioners. One can use these games as entrypoints to talking with the general public about archaeology. One can also attempt to work with game developers on improving archaeology’s representation. Lastly one can create archaeology-themed games as a way to introduce more accurate portrayals of what archaeology is and what archaeologists actually do. Ethics is central to archaeological reception, supported by the work of L. Meghan Dennis (University of York).

### Games as Archaeology

Because games are created by people for other people to use, the become part of modern day material culture. As seen in the list of projects below, archaeologists treat game media as both physical and digital artifacts. Games are also archaeological sites when one considers various files recorded to game media, each with a specific location and function. Games are landscapes, too, inviting players to engage with the content.

### Archaeogaming Projects Past and Present

#### The Atari Burial Ground

The first archaeogaming project actually happened in a desert landfill in Alamogordo, New Mexico. In 1983 Atari, Inc. buried hundreds of thousands of unsold/returned video game cartridges, which was the cheapest and most expedient way to dispose of its e-waste. Although the dumping was documented by the Alamogordo Daily News and the New York Times, it became an urban legend in the video game community. The legend stated that Atari’s game E.T.: The Extraterrestrial (1982) was the worst video game of all time, and Atari in its shame decided to dump millions of copies in a landfill, covering them with a layer of concrete and then with 10 m of dirt and rubbish. In 2013, a Canadian company, Fuel Entertainment, received the rights from the city of Alamogordo to excavate the landfill in search of the games, filming the project. City waste management expert Joe Lewandowsky conducted photogrammetry to pinpoint the location of where to dig. Archaeologists were invited to assist in the recovery and analysis of the games in April 2014. While for some people the excavation would prove that Atari did dispose of their games in the desert, the archaeologists were interested to learn where the archaeological evidence and details of the urban legend both agreed and diverged. This was the first deposition of an assemblage of 20th-century video games, which for many people growing up in the 1980s had become their cultural heritage. About 800,000 games were actually buried (not millions), and E.T. proved to be one of over 40 different titles dumped in 1983. After the excavation ended, the city donated some of the games to museums worldwide and then auctioned the rest on Ebay, using the proceeds to pay back Alamogordo for equipment and labor, and also to rehabilitate the local museum.

#### Buried

The Twine game Buried (URL: http://taracopplestone.co.uk/buried.html), created by Tara Copplestone and Luke Botham for the University of York’s 2014 Heritage Jame, is an example of ergodic literature (a text-based game) that interprets the concept of burial in both academic and personal contexts. You play as an archaeologist, and the game is faithful to actual day-to-day archaeology and the archaeologist’s routine. Compare this to the over-the-top action of Tomb Raider where archaeology is treated more as set-dressing and an excuse for advancing the series’ story.

#### The No Man’s Sky Archaeological Survey

All games lend themselves to archaeological investigation, but only a few contain permanent human populations of players who have made game-spaces their own, investing them with history and lore independent of the game developers’ intentions. One such game is Eve Online. Another is No Man’s Sky. At its inception, the No Man’s Sky Archaeological Survey intended to explore the procedurally generated, universe-sized universe of the game, documenting examples of “machine-created culture” created through the game’s algorithms and code. What happened instead became an investigation of the human-settled region of the “Galactic Hub”, an enclave of hundreds of citizen scientist-players forced to migrate en masse to another region of the universe because of a catastrophic climate change event. On August 11, 2017, Hello Games released the version 1.3 update, “Atlas Rises”, which reset all of the planetary climates and biomes on a quintillion worlds overnight. Players with bases and farms on “Paradise”-class worlds awoke to extreme cold, heat, and toxicity. They abandoned their habitations and left behind messages for others to read, some being notes of farewell, and others with forwarding addresses. Learning about what happened, who these players were, how they settled the galaxy, and what they left behind became the renewed focus of the NMSAS project. Think of it as Roanoke or Herculaneum in space.

#### Reverse-Engineering Digital Games as Archaeological Practice

Prof. John Aycock (University of Calgary) works at the intersection of archaeology and computer science. His work in reverse-engineering games of the 1980s and 1990s explores the necessity of understanding how hardware and software interface with each other to create a gaming experience, while also deconstructing disk images to understand how games actually work from a technical perspective, identifying precisely where files live on the original game media. His current projects include analyzing full-motion video formats in games, understanding game development through analyzing underlying code, and early attempts at digital rights management (DRM, or copy protection) on physical game media.

#### Purpose

Digital games specifically (and software generally) are the new habitations of the late 20th and early 21st centuries. Billions of people enter synthetic spaces every day to work, communicate, make a living, be entertained, to create, all by passing through the modern day looking glass of the smartphone screen, desktop display, or television. The nature of these digital habitations, their use, construction, and disposal, lends itself to archaeological interpretation. It is a new field within archaeology where we can attempt to understand human occupation and development in digital built environments.

### Is Archaeogaming Archaeology? A Future of the Discipline.

When most people think of archaeology they consider it to be focused on ancient cultures and artifacts. However, in the past 30 years, archaeology of the recent past (and of Late Capitalism) has become more mainstream. Archaeology is the study of how people interact with things and within their environment regardless of time period. William Rathje’s Tucson Garbage Project (begun in 1973) studied people’s everyday household rubbish, comparing the material evidence with anonymous interviews with the residents about what they threw out. In 2018 Justin Walsh and Alice Gorman lead the project recording the history of use of the International Space Station, using tens of thousands of photographs taken from inside the ISS to reconstruct how the interior changed over time.

With archaeogaming, one can work with physical artifacts such as game tapes, cartridges, CDs, and hardware, but one can also conduct archaeological investigation within the games contained on that media. Software programs are built environments and through their daily use by billions of people become contemporary examples of material culture and built heritage. Games contain art and architecture, a history of use, object biographies, game- and user-created histories, and change over time through use and development. Archaeogaming is an entrypoint to understanding the wider world of software archaeologically. When studying the past, archaeologists rely on material evidence, context, and primary sources to reconstruct an understanding of people and how they lived. With software, similar archaeological questions are asked of populations of creators and users, towards an archaeology of the future.

### Exercises

1. Play a game featuring an archaeologist or archaeology and describe how the archaeology as represented differs from actual practice.
2. Write your own mini-game that includes either archaeology or a character who is an archaeologist. An accessible tool with which to craft a game is [Twine](http://twinery.org). Tara Copplestone has a [guide to twine for archaeologists](https://taracopplestone.gitbooks.io/twine-4-archaeology-dummies/content/getting_started.html) that can get you started; the [Twine Cookbook](https://twinery.org/cookbook/) contains code examples for achieving particular effects. One in particular that might appeal to archaeologists is the potential for triggering passages of text or parts of a game based on the players' [actual physical locations](https://twinery.org/cookbook/geolocation/harlowe/harlowe_geolocation.html)
3. Pick a game that has neither archeologists nor archaeology (or cultures, monuments, artifacts, etc.) in it and describe how it is an archaeological artifact, site, and/or landscape.
4. Deconstruct a piece of physical game media as an archaeologist might, and write a site report based on what you find.

### Further Reading

The following works will help situate 'archaeogaming' for you in broader archaeological practice:
@aycock_reinhard_2017, @meyers_reinhard_2017, @reinhard_2015, @reinhard_2017, and @reinhard_2018.
